### ISSUE TITLE
opencdms-server

### ISSUE THREAD

**Issue by isedwards** [opencdms-dev/legacy-opencdms-api#2]
Raise future issues for:
- [ ] Local Application Database for user management, application configuration and database management
- [ ] Authentication
- [ ] Language translation
- [ ] Review `pygeoapi` approach to exposing a web API and take a similar approach
- [ ] Web API design will be informed by `pyopencdms` Python API and OGC API (particularly EDR)
